### ISSUE TITLE
Look into jest-glamor-react

### ISSUE THREAD

**Issue by kentcdodds** [justinobney/react-wallaby-starter#1]
Because you're using create-react-app, you wont be able to do this (reasonably) without ejecting and upgrading Jest, but since you're using glamorous, you really should think about using [jest-glamor-react](https://github.com/kentcdodds/jest-glamor-react)!

**Comment by justinobney** [comment]
@kentcdodds I dont know if this (afb11499fe464bdd6b596a4975e837a3fd864354) is "reasonable" per-se, but as a naive developer:  😝 😎

**Comment by justinobney** [comment]
also, this probably works because i am not using `npm test`, i am using wallabyJS to run my tests...

![image](https://cloud.githubusercontent.com/assets/1054188/25535458/bf0e5c38-2bfc-11e7-8653-3b4a47d37ea8.png)

**Comment by kentcdodds** [comment]
Nice!
